#!/usr/bin/env bash
# factors-env.sh — emit_factors_env FACTORS_JSON DEST_DIR
#
# Writes <dest>/factors.env atomically: the per-family co2 factors and derived
# physics constants as plain shell assignments, so the statusline render path
# never runs jq against factors.json (or anything else heavier than `source`).
#
# The file is SOURCED by the user's statusline, so every value passes the same
# numeric case-guard recompute.sh uses — a malformed factors.json can never
# inject shell into the render path.

emit_factors_env() {
  local factors="$1" dest_dir="$2"
  local tmp dest v
  dest="${dest_dir}/factors.env"
  tmp="${dest}.tmp.$$"

  local fab_in fab_out opus_in opus_out son_in son_out hai_in hai_out cif water_per_wh emb removal_rate constants
  constants="$(dirname "$factors")/offset-constants.json"
  removal_rate="$(jq -r '.removal_usd_per_tonne // 227' "$constants" 2>/dev/null)" || removal_rate=227
  fab_in="$(jq -r '.models.fable.input // 156' "$factors")"
  fab_out="$(jq -r '.models.fable.output // 3304' "$factors")"
  opus_in="$(jq -r '.models.opus.input' "$factors")"
  opus_out="$(jq -r '.models.opus.output' "$factors")"
  son_in="$(jq -r '.models.sonnet.input' "$factors")"
  son_out="$(jq -r '.models.sonnet.output' "$factors")"
  hai_in="$(jq -r '.models.haiku.input' "$factors")"
  hai_out="$(jq -r '.models.haiku.output' "$factors")"
  cif="$(jq -r '.physics.grid_cif_g_per_wh.value // 0.287' "$factors")"
  emb="$(jq -r '.physics.embodied_gco2e_per_kwh.value // 44.1' "$factors")"
  water_per_wh="$(jq -r '.physics | "\(.wue_onsite_l_per_kwh.value // 0.18) \(.pue.value // 1.14) \(.wue_offsite_l_per_kwh.value // 5.11)"' "$factors" |
    LC_ALL=C awk '{printf "%.10f", $1 / $2 + $3}')"

  for v in "$fab_in" "$fab_out" "$opus_in" "$opus_out" "$son_in" "$son_out" \
    "$hai_in" "$hai_out" "$cif" "$water_per_wh" "$emb" "$removal_rate"; do
    case "$v" in
    '' | *[!0-9.eE+-]*)
      echo "factors-env: non-numeric value ('${v}'); refusing to write factors.env" >&2
      return 1
      ;;
    esac
  done

  {
    echo "# generated by carbon-ledger (setup.sh / recompute.sh) — do not edit"
    echo "CL_F_FAB_IN=${fab_in}"
    echo "CL_F_FAB_OUT=${fab_out}"
    echo "CL_F_OPUS_IN=${opus_in}"
    echo "CL_F_OPUS_OUT=${opus_out}"
    echo "CL_F_SON_IN=${son_in}"
    echo "CL_F_SON_OUT=${son_out}"
    echo "CL_F_HAI_IN=${hai_in}"
    echo "CL_F_HAI_OUT=${hai_out}"
    echo "CL_CIF=${cif}"
    echo "CL_WATER_PER_WH=${water_per_wh}"
    echo "CL_EMB_PER_WH=${emb}"
    echo "CL_REMOVAL_USD_PER_T=${removal_rate}"
  } >"$tmp" && mv -f "$tmp" "$dest"
}

# refresh_factors_env_if_stale FACTORS_JSON DEST_DIR
#
# factors.env is a CACHE of two JSON files, and a cache with no invalidation is
# a slow-acting bug. It happened: the removal price moved from $160 to $227 a
# tonne in data/offset-constants.json, every path that reads that file directly
# picked the new figure up, and the statusline — which reads only this cache —
# went on pricing each session at the old rate for days. Nothing failed, no test
# went red, and the two figures on screen simply disagreed by thirty percent.
#
# So the mtimes decide, compared as NUMBERS and not with -nt. `-nt` is false when
# two files share a timestamp, and filesystem mtimes here have one-second
# granularity — so an edit landing in the same second as the last rebuild is
# exactly the case the operator would least expect to be missed. The cache is
# treated as stale unless it is strictly newer than every source, which at worst
# costs one redundant rebuild and never skips a real one.
#
# A rebuild is a handful of jq calls off the render path (this runs in the Stop
# hook, never in the statusline), and it cannot fail the caller: emit_factors_env
# already refuses to write anything non-numeric, and a stale-but-valid cache
# beats no cache at all.
_cl_mtime() { # portable mtime in epoch seconds; 0 when the file is absent
  stat -f %m "$1" 2>/dev/null || stat -c %Y "$1" 2>/dev/null || echo 0
}

refresh_factors_env_if_stale() {
  local factors="$1" dest_dir="$2"
  local dest constants newest m
  dest="${dest_dir}/factors.env"
  constants="$(dirname "$factors")/offset-constants.json"

  [ -f "$factors" ] || return 0
  if [ -f "$dest" ]; then
    newest=0
    for m in "$factors" "$constants"; do
      [ -f "$m" ] || continue
      m="$(_cl_mtime "$m")"
      [ "${m:-0}" -gt "$newest" ] 2>/dev/null && newest="$m"
    done
    if [ "$(_cl_mtime "$dest")" -gt "$newest" ] 2>/dev/null; then
      return 0
    fi
  fi
  emit_factors_env "$factors" "$dest_dir" || return 0
}
